searchd
{
    listen = 9306:mysql
    log = /var/lib/manticore/searchd.log
    query_log = /var/lib/manticore/query.log
    pid_file = /var/lib/manticore/searchd.pid
    data_dir = /var/lib/manticore
}